Authentication/urls.py
from django.urls import path
from Authentication.views import *

app_name = 'Authentication'

urlpatterns = [
    path('', showAuthNav, name='auth_nav'),
    path('login', login, name='login'),
    path('nav', showNav, name='nav'),
    path('logout', logout, name='logout'),
    path('register',showRegister, name='register'),
    path('register-user',showUserRegPage,name='register-user'),
    path('register-label',showLabelRegPage, name='register-label')
]

Marmut_F13/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Authentication.urls')),
    path('album/', include('SongAlbum.urls')),
    path('dashboard/', include('dashboard.urls')),  
    path('', include('playpodcast.urls')),
    path('', include('viewchart.urls')),
    path('', include('managepod.urls')),
    path('album/', include('SongAlbum.urls')),
    path('manageplaylist/', include('manageplaylist.urls')),
]

SongAlbum/urls.py
from django.urls import path
from SongAlbum.views import *

app_name = 'SongAlbum'

urlpatterns = [
    path('album-labeled', showAlbumLabel, name='show_album_label'),
    path('album', showAlbum, name='show_album'),
    path('song-labeled/<uuid:album_id>/', showSongLabel, name='show_song_label'),
    path('song/<uuid:album_id>/', showSong, name='show_song'),
    path('royalty', showRoyaltyCheck, name='royalty_check'),
    path('new-album', addAlbum, name='add_album'),
    path('new-song/<uuid:album_id>/', addSong, name='add_song'),
    path('del-song/<uuid:song_id>/<uuid:album_id>/', deleteSong, name='del_song'),
    path('del-song-labeled/<uuid:song_id>/<uuid:album_id>/', deleteSongLabel, name='del_song_label'),
    path('del-album/<uuid:album_id>/', deleteAlbum, name='del_album'),
    path('del-album-labeled/<uuid:album_id>/', deleteAlbumLabel, name='del_album_label'),
]

Authentication/views.py
from django.shortcuts import redirect, render
import random, uuid
from django.http import HttpResponseRedirect
from django.db import connection, connections
from django.urls import reverse


# Fungsi yang digunakan untuk melakukan login
def login(request):
    if request.method == 'POST':
        email = request.POST.get("email")
        password = request.POST.get("password")

        print(request.COOKIES.get('login'))
        user, is_label = authenticate(email, password)
        response = HttpResponseRedirect(reverse("dashboard:dashboard"))
        if(is_label == True):
            response.set_cookie("login", user[0][2])
        else:
            response.set_cookie("login", user[0][0])
        return response
    
    return render(request, 'loginPage.html')

#Fungsi yang digunakan untuk menampilkan halaman depan login
def showAuthNav(request):
    context = {
        'show_navbar' : False,
    }
    return render(request, "authNav.html", context)

#Fungsi yang digunakan untuk menampilkan navbar utama
def showNav(request):
    email = request.COOKIES.get("login")
    context = get_user_data(email)

    return render(request, "base.html", context)

#Fungsi yang digunakan untuk memproses logout
def logout(request):
    response = HttpResponseRedirect(reverse('Authentication:auth_nav'))
    response.delete_cookie('email')
    
    return response

#Fungsi yang digunakan untuk memproses query SELECT
def selectQuery(query):
    SET_QUERY =  "SET search_path to marmut;"
    query = SET_QUERY + query
    with connection.cursor() as cursor:
        cursor.execute(query)
        result = cursor.fetchall()
        
        return result
    
#Fungsi yang digunakan untuk memproses query INSERT, DELETE, UPDATE
def modifyQuery(query):
    SET_QUERY =  "SET search_path to marmut;"
    query = SET_QUERY + query
    with connection.cursor() as cursor:
        cursor.execute(query)

#Fungsi yang digunakan untuk mengambil role dari pengguna berdasarkan email
def checkRole(email):
    artist, songwriter, podcaster, label = False, False, False, False
    hak_cipta_artist, hak_cipta_songwriter, hak_cipta_label = "", "", ""
    LABEL_QUERY = f"""
        SELECT * FROM LABEL
        WHERE email = '{email}'
    """
    user = selectQuery(LABEL_QUERY)
    print(user)
    if(len(user) != 0):
        label = True
        hak_cipta_label = user[0][2]
        return {'artist':artist, 'songwriter':songwriter, 'podcaster':podcaster, 'label':label, 'hak_cipta':{'artist' : hak_cipta_artist, 'songwriter' : hak_cipta_songwriter, 'label' : hak_cipta_label}}

    ARTIST_QUERY = f"""
        SELECT * FROM ARTIST
        WHERE email_akun = '{email}'
    """
    user = selectQuery(ARTIST_QUERY)
    if (len(user) != 0):
        artist = True 
        hak_cipta_artist = user[0][2]

    SONGWRITER_QUERY = f"""
        SELECT * FROM SONGWRITER
        WHERE email_akun = '{email}'
    """
    user = selectQuery(SONGWRITER_QUERY)
    if (len(user) != 0):
        songwriter = True 
        hak_cipta_songwriter = user[0][2]
        
    PODCASTER_QUERY = f"""
        SELECT * FROM PODCASTER
        WHERE email = '{email}'
    """
    user = selectQuery(PODCASTER_QUERY)
    if (len(user) != 0):
        podcaster = True

    return {'artist':artist, 'songwriter':songwriter, 'podcaster':podcaster, 'label':label, 'hak_cipta':{'artist' : hak_cipta_artist, 'songwriter' : hak_cipta_songwriter, 'label' : hak_cipta_label}}

#Fungsi yang digunakan untuk mengambil data user dan kembalikan dalam dictionary
def get_user_data(email):
    context = {}
    USER_QUERY = f"""
        SELECT * FROM AKUN
        WHERE email = '{email}'
    """

    LABEL_QUERY = f"""
        SELECT * FROM LABEL
        WHERE email = '{email}'
    """
    user = selectQuery(USER_QUERY)
    if len(user) != 0:
        context = {
            "show_navbar" : True,
            "premium" : check_premium(email),
            "user_email": user[0][0],
            "user_password": user[0][1],
            "user_name": user[0][2],
            "user_gender": 'Female' if user[0][3] == 0 else 'Male',
            "user_tempat_lahir": user[0][4],
            "user_tanggal_lahir": user[0][5],
            "user_is_verified": user[0][6],
            "user_kota_asal": user[0][7],
            "user_role": checkRole(email=user[0][0])
        }
        print("User data found:", context)  # Debug statement
    else:
        user = selectQuery(LABEL_QUERY)
        if len(user) != 0:
            context = {
                "show_navbar" : True,
                "user_id": user[0][0],
                "user_name": user[0][1],
                "user_email": user[0][2],
                "user_password": user[0][3],
                "user_kontak": user[0][4],
                "user_role": checkRole(email=user[0][2])
            }
    return context


def authenticate(email, password):
    USER_QUERY = f"""
        SELECT * FROM  AKUN
        WHERE email = '{email}' AND password = '{password}';
    """

    LABEL_QUERY = f"""
        SELECT * FROM LABEL
        WHERE email = '{email}' AND password = '{password}';
    """

    user = selectQuery(USER_QUERY)
    if (len(user) != 0):
        label = False
        return user, label
    else:
        user = selectQuery(LABEL_QUERY)
        label = True
        return user, label

#Fungsi yang digunakan untuk mengecek apakah pengguna Premium
def check_premium(email):
    SUBSCRIPTION_QUERY = f"""
        SELECT * FROM PREMIUM 
        WHERE email = '{email}'
    """

    user = selectQuery(SUBSCRIPTION_QUERY)
    if(len(user) != 0):
        return True
    return False

    
def showRegister(request):
    context = {
        'show_navbar' : False,
    }
    return render(request, "register.html", context)

def showUserRegPage(request):
    if request.method == 'POST':
        email = request.POST.get('email')
        password = request.POST.get('password')
        nama = request.POST.get('nama')
        gender = request.POST.get('gender')
        if(gender) == ('Laki-laki'):
            no_gender = 1
        else:
            no_gender = 0
        tempat_lahir = request.POST.get('tempat_lahir')
        tanggal_lahir = request.POST.get('tanggal_lahir')
        kota_asal = request.POST.get('kota_asal')
        roles = request.POST.getlist('role')
        if len(roles) == 0:
            verified = False
        else:
            verified = True

        with connection.cursor() as cursor:
            try:
                cursor.execute("set search_path to marmut;")
                cursor.execute(f"INSERT INTO AKUN(email, password, nama, gender, tempat_lahir, tanggal_lahir, is_verified, kota_asal) values ('{email}', '{password}', '{nama}', '{no_gender}', '{tempat_lahir}', '{tanggal_lahir}', '{verified}', '{kota_asal}');")
                for i in roles:
                    if i == "Podcaster":
                        cursor.execute(f"INSERT INTO PODCASTER(email) values ('{email}');")
                    elif i == "Artist":
                        cursor.execute('SELECT * FROM PEMILIK_HAK_CIPTA')
                        hak_cipta = cursor.fetchall()
                        id_hak_cipta = str(random.choice(hak_cipta)[0])
                        id = str(uuid.uuid4())
                        cursor.execute(f"INSERT INTO ARTIST(id, email_akun, id_pemilik_hak_cipta) values ('{id}', '{email}', '{id_hak_cipta}');")
                    elif i == "Songwriter":
                        cursor.execute('SELECT * FROM PEMILIK_HAK_CIPTA')
                        hak_cipta = cursor.fetchall()
                        id_hak_cipta = str(random.choice(hak_cipta)[0])
                        id = str(uuid.uuid4())
                        cursor.execute(f"INSERT INTO SONGWRITER(id, email_akun, id_pemilik_hak_cipta) values ('{id}', '{email}', '{id_hak_cipta}');")
                
                print('Registrasi berhasil!')

            except Exception as e:
                msg = str(e).split('\n')[0]
                print( f'Registrasi gagal: {msg}')
                return render(request, "register_pengguna.html")

            return redirect('Authentication:login')
        
    context = {
        'show_navbar' : False,
        'user' : True,
        'label' : False,
        "is_logged_in": False
    }
    return render(request, "userReg.html", context)

def showLabelRegPage(request):
    if request.method == 'POST':
        email = request.POST.get('email')
        password = request.POST.get('password')
        nama = request.POST.get('nama')
        kontak = request.POST.get('kontak')
        id = str(uuid.uuid4())

        with connection.cursor() as cursor:
            try:
                cursor.execute('set search_path to marmut')
                cursor.execute('SELECT * FROM PEMILIK_HAK_CIPTA')
                hak_cipta = cursor.fetchall()
                id_hak_cipta = str(random.choice(hak_cipta)[0])
                cursor.execute(f"INSERT INTO LABEL(id, nama, email, password, kontak, id_pemilik_hak_cipta) values ('{id}', '{nama}', '{email}', '{password}', '{kontak}', '{id_hak_cipta}')")
            
            except Exception as e:
                msg = str(e).split('\n')[0]
                print( f'Registrasi gagal: {msg}')
                return render(request, "register_label.html")
            
            return redirect('Authentication:login')
            
    context = {
        'show_navbar' : False,
        'user' : False,
        'label' : True,
        'logged_in' : False,
    }

    return render(request, "labelReg.html", context)

Authentication/templates/authNav.html
{% extends "base.html" %}
{% load static %}

{% block content %}
<div class="grid grid-cols-2">
    <div class="relative group bg-red-500 overflow-hidden">
        <a href="{% url 'Authentication:login' %}">
            <img src="https://imagizer.imageshack.com/img922/9452/V8LfQK.png" alt="eddd5c28-c1ac-4cd0-8727-ce73b7ad1b54" alt="Image 1" class="w-full h-full object-cover transition-transform duration-300 group-hover:scale-110">
            <div class="absolute bottom-0 left-0 w-full text-center p-4 mb-24 text-8xl bg-black bg-opacity-50 text-white transition-transform duration-300 group-hover:scale-110">
                LOGIN
            </div>
        </a>
    </div>
    
    <div class="relative group bg-red-500 overflow-hidden">
        <a href="{% url 'Authentication:register' %}">
            <img src="https://imagizer.imageshack.com/img923/9537/TjjVZ0.png" alt="eddd5c28-c1ac-4cd0-8727-ce73b7ad1b54" alt="Image 1" class="w-full h-full object-cover transition-transform duration-300 group-hover:scale-110">
            <div class="absolute bottom-0 left-0 w-full text-center p-4 mb-24 text-8xl bg-black bg-opacity-50 text-white transition-transform duration-300 group-hover:scale-110">
                REGISTER
            </div>
        </a>
    </div>
</div>
{% endblock content %}

Authentication/templates/labelReg.html
{% extends "base.html" %}
{% load static %}

{% block content %}
<div class="flex justify-between h-screen">
    

    <div class="w-2/3 p-8 h-full flex flex-col justify-center" style="background-image: url('https://i.ibb.co.com/Yb6PQ9F/Desktop-1.jpg'); background-repeat: no-repeat; background-size: cover; background-position: center;">
        <h2 class="text-5xl font-bold mb-8 text-lightOrange text-center">REGISTRASI</h2>
        <form class="space-y-4">
            <div class="flex flex-col">
                <label for="email" class="text-sm mb-1 text-lightOrange">Email:</label>
                <input type="email" id="email" name="email" class="rounded border py-2 px-3" required>
            </div>
            <div class="flex flex-col">
                <label for="password" class="text-sm mb-1 text-lightOrange">Password:</label>
                <input type="password" id="password" name="password" class="rounded border py-2 px-3" required>
            </div>
            <div class="flex flex-col">
                <label for="nama" class="text-sm mb-1 text-lightOrange">Nama:</label>
                <input type="text" id="nama" name="nama" class="rounded border py-2 px-3" required>
            </div>
            <div class="flex flex-col">
                <label for="kontak" class="text-sm mb-1 text-lightOrange">Kontak:</label>
                <input type="text" id="kontak" name="kontak" class="rounded border py-2 px-3" required>
            </div>
            <button type="submit" class="bg-oxfordBlue text-lightOrange py-2 px-4 rounded-full w-full hover:bg-glaucous">Register</button>
        </form>
        <button id="kembaliBtn" class="bg-glaucous text-lightOrange py-2 px-4 rounded-full hover:bg-oxfordBlue mt-4 block mx-auto">Kembali</button>
    </div>
    <div class="hidden bg-cover lg:block lg:w-1/3" style="background-image:url('https://i.ibb.co.com/8PBpVv2/label.jpg')">

    </div>
</div>

<script>
    document.getElementById("kembaliBtn").addEventListener("click", function() {
        window.location.href = "{% url 'Authentication:login' %}";
    });
</script>
{% endblock content %}

Authentication/templates/loginPage.html
{% extends "base.html" %}
{% load static %}

{% block content %}
<div class="flex bg-gradient-to-tl from-[#09173E] to-[#0F1C46] min-h-screen rounded-lg shadow-lg overflow-hidden mx-auto max-w-full">
    <div class="hidden bg-cover lg:block lg:w-2/3" style="background-image:url('https://i.ibb.co.com/3kJnswM/DALL-E-2024-04-29-00-43-07-Create-a-landscape-image-of-a-whimsical-marmot-character-in-a-city-street.png')">
    </div>
    <div class="flex flex-col justify-center w-full p-8 lg:w-1/3">
        <h2 class="mb-4 text-4xl font-bold text-center text-white">MARMUT - F13</h2>
        <p class="mb-8 text-lg text-center text-white">Welcome back!</p>
        
        <form class="space-y-4" method="POST" action="">
            {% csrf_token %}
            <div>
                <label for="email" class="block mb-1 text-sm font-bold text-white">Email</label>
                <input name="email" class="block w-full px-4 py-2 text-gray-700 bg-gray-200 border border-gray-300 rounded appearance-none focus:outline-none focus:shadow-outline" type="text"/>
            </div>
            <div class="flex items-center justify-between">
                <label for="password" class="block mb-1 text-sm font-bold text-white">Password</label>
                <a href="" class="inline-block text-sm text-white rounded hover:bg-opacity-25 hover:text-[#6D7DB1]">Forgot Password?</a>
            </div>
            <input name="password" class="block w-full px-4 py-2 text-gray-700 bg-gray-200 border border-gray-300 rounded appearance-none focus:outline-none focus:shadow-outline" type="password" />
            <a href="{% url 'Authentication:login' %}" class="block w-full px-4 py-2" >
                <button class="w-full px-4 py-2 font-bold text-white rounded-full bg-[#6D7DB1] hover:bg-[#FADCBA] hover:text-[#6D7DB1]">Login</button>
            </a>
        </form>
        
        <div class="flex items-center justify-center mt-6">
            <span class="border-b w-1/7"></span>
            <p class="text-xs text-white">Don't have an account?</p>
            <a href="{% url 'Authentication:register' %}" class="px-1 text-xs font-bold text-white hover:text-[#6D7DB1]">Sign Up Here</a>
            <span class="border-b w-1/7"></span>
        </div>
    </div>
</div>
{% endblock content %}

Authentication/templates/register.html
{% extends "base.html" %}
{% load static %}

{% block content %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Register Page</title>
    <link href="https://cdn.jsdelivr.net/npm/tailwindcss@2.2.19/dist/tailwind.min.css" rel="stylesheet">
</head>
<body class="bg-lightOrange">
    <div class="container mx-auto py-12">
        <h1 class="text-4xl font-bold text-center mb-8">REGISTER AS</h1>
        <div class="grid grid-cols-2 gap-8">
            <div class="relative bg-white rounded-lg overflow-hidden shadow-md">
                <a href="{% url 'Authentication:register-label' %}">
                    <img src="https://i.ibb.co.com/8PBpVv2/label.jpg" alt="Image 1" class="w-full h-120 object-cover">
                    <div class="absolute top-0 left-0 w-full h-full flex items-center justify-center text-center text-white text-xl font-bold bg-black bg-opacity-50">
                        LABEL
                    </div>
                </a>
            </div>
            <div class="relative bg-white rounded-lg overflow-hidden shadow-md">
                <a href="{% url 'Authentication:register-user' %}">
                    <img src="https://i.ibb.co.com/C6JMXmd/user.jpg" alt="Image 2" class="w-full h-120 object-cover">
                    <div class="absolute top-0 left-0 w-full h-full flex items-center justify-center text-center text-white text-xl font-bold bg-black bg-opacity-50">
                        USER
                    </div>
                </a>
            </div>
        </div>
    </div>
</body>
</html>
{% endblock content %}

Authentication/templates/userReg.html
{% extends "base.html" %}
{% load static %}

{% block content %}
<div class="flex justify-between">
    <div class="hidden bg-cover lg:block lg:w-1/3" style="background-image:url('https://i.ibb.co.com/C6JMXmd/user.jpg')">
    </div>
    <div class="w-2/3 p-8" style="background-image: url('https://i.ibb.co.com/Yb6PQ9F/Desktop-1.jpg'); background-repeat: no-repeat; background-size: cover; background-position: center;">
        <h2 class="text-5xl font-bold mb-8 text-lightOrange text-center">REGISTRASI</h2>
        <form class="space-y-4" method="post" action="{% url 'Authentication:register-user' %}">
            {% csrf_token %}
            <div class="flex flex-col">
                <label for="email" class="text-sm mb-1 text-lightOrange">Email:</label>
                <input type="email" id="email" name="email" class="rounded border py-2 px-3" required>
            </div>
            <div class="flex flex-col">
                <label for="password" class="text-sm mb-1 text-lightOrange">Password:</label>
                <input type="password" id="password" name="password" class="rounded border py-2 px-3" required>
            </div>
            <div class="flex flex-col">
                <label for="nama" class="text-sm mb-1 text-lightOrange">Nama:</label>
                <input type="text" id="nama" name="nama" class="rounded border py-2 px-3" required>
            </div>
            <div class="flex flex-col">
                <label for="gender" class="text-sm mb-1 text-lightOrange">Gender:</label>
                <select id="gender" name="gender" class="rounded border py-2 px-3" required>
                    <option value="Laki-laki" class="text-lightOrange">Laki-laki</option>
                    <option value="Perempuan" class="text-lightOrange">Perempuan</option>
                </select>
            </div>
            <div class="flex flex-col">
                <label for="tempat_lahir" class="text-sm mb-1 text-lightOrange">Tempat Lahir:</label>
                <input type="text" id="tempat_lahir" name="tempat_lahir" class="rounded border py-2 px-3" required>
            </div>
            <div class="flex flex-col">
                <label for="tanggal_lahir" class="text-sm mb-1 text-lightOrange">Tanggal Lahir:</label>
                <input type="date" id="tanggal_lahir" name="tanggal_lahir" class="rounded border py-2 px-3" required>
            </div>
            <div class="flex flex-col">
                <label for="kota_asal" class="text-sm mb-1 text-lightOrange">Kota Asal:</label>
                <input type="text" id="kota_asal" name="kota_asal" class="rounded border py-2 px-3" required>
            </div>
            <div class="flex flex-col">
                <label class="text-sm mb-1 text-lightOrange">Role:</label>
                <div class="flex items-center space-x-4">
                    <input type="checkbox" id="podcaster" name="role" value="Podcaster" class="rounded border">
                    <label for="podcaster" class="text-sm text-lightOrange" style="margin-right: 330px;">Podcaster</label>
                    <input type="checkbox" id="artist" name="role" value="Artist" class="rounded border">
                    <label for="artist" class="text-sm text-lightOrange" style="margin-right: 330px;">Artist</label>
                    <input type="checkbox" id="songwriter" name="role" value="Songwriter" class="rounded border">
                    <label for="songwriter" class="text-sm text-lightOrange">Songwriter</label>
                </div>
            </div>
            <button type="submit" class="bg-oxfordBlue text-lightOrange py-2 px-4 rounded-full w-full hover:bg-glaucous">Register</button>
        </form>
        <button id="kembaliBtn" class="bg-glaucous text-lightOrange py-2 px-4 rounded-full hover:bg-oxfordBlue mt-4 block mx-auto">Kembali</button>
    </div>
</div>

<script>
    document.getElementById("kembaliBtn").addEventListener("click", function() {
        window.location.href = "{% url 'Authentication:login' %}";
    });
</script>
{% endblock content %}