Marmut_F13/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Authentication.urls')),
    path('album/', include('SongAlbum.urls')),
    path('dashboard/', include('dashboard.urls')),  
    path('', include('playpodcast.urls')),
    path('', include('viewchart.urls')),
    path('', include('managepod.urls')),
    path('album/', include('SongAlbum.urls')),
    path('manageplaylist/', include('manageplaylist.urls')),
]

SongAlbum/urls.py
from django.urls import path
from SongAlbum.views import *

app_name = 'SongAlbum'

urlpatterns = [
    path('album-labeled', showAlbumLabel, name='show_album_label'),
    path('album', showAlbum, name='show_album'),
    path('song-labeled/<uuid:album_id>/', showSongLabel, name='show_song_label'),
    path('song/<uuid:album_id>/', showSong, name='show_song'),
    path('royalty', showRoyaltyCheck, name='royalty_check'),
    path('new-album', addAlbum, name='add_album'),
    path('new-song/<uuid:album_id>/', addSong, name='add_song'),
    path('del-song/<uuid:song_id>/<uuid:album_id>/', deleteSong, name='del_song'),
    path('del-song-labeled/<uuid:song_id>/<uuid:album_id>/', deleteSongLabel, name='del_song_label'),
    path('del-album/<uuid:album_id>/', deleteAlbum, name='del_album'),
    path('del-album-labeled/<uuid:album_id>/', deleteAlbumLabel, name='del_album_label'),
]

manageplaylist/urls.py
from django.urls import path
from manageplaylist.views import *;

app_name = 'manageplaylist'

urlpatterns = [
    path('', showManagePlaylistPage, name='manage-playlist'),
    path('playlistdetail/<str:id_playlist>', showPlaylistPage, name='userplaylistdetail'),
    path('playingsong/<str:id_konten>', showPlayingSongPage, name='playingsong'),
    path('add-playlist/', add_playlist, name='add-playlist'),
    path('edit-playlist/<str:id_playlist>', edit_playlist, name='edit-playlist'),
    path('delete-playlist/<str:id_playlist>', delete_playlist, name='delete-playlist'),
    path('add-song/<str:id_playlist>', add_song, name="add-song"),
    path('add-song-to-playlist/<str:id_konten>', add_song_to_playlist, name="add-song-to-playlist"),
    path('delete-song/<str:id_playlist>/<str:id_konten>', delete_song, name='delete-song')
]

manageplaylist/models.py
from django.db import models

# Create your models here.

manageplaylist/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import redirect, render
from django.urls import reverse
from django.db import connection as conn
from datetime import date
import uuid

def showManagePlaylistPage(request):
    email = request.COOKIES.get("login")

    with conn.cursor() as cursor:
        try:
            cursor.execute("Set search_path to marmut;")
            cursor.execute("SELECT * FROM USER_PLAYLIST WHERE email_pembuat = %s", [email])
            rows = cursor.fetchall()
            playlists = [
                {
                'id':row[1],
                'judul': row[2],
                'jumlah_lagu': row[4],
                'total_durasi': row[7],
                }
                for row in rows
            ]

            context = {
                'playlists': playlists,
                'show_navbar': True,
            }

            
        except:
            context = {
                'show_navbar': True,
            }
            print('belum ada playlist')

    return render(request, "manageplaylist.html", context)

def add_playlist(request):
    if request.method == "POST":
        email = request.COOKIES.get("login")
        id_user_playlist = str(uuid.uuid4())
        judul = request.POST.get('judul')
        deskripsi = request.POST.get('deskripsi')
        id_playlist = str(uuid.uuid4())


        with conn.cursor() as cursor:
            cursor.execute("Set search_path to marmut;")
            cursor.execute("""
                INSERT INTO PLAYLIST (id)
                VALUES (%s)
            """,[id_playlist])
            
            cursor.execute("""
                INSERT INTO USER_PLAYLIST (email_pembuat, id_user_playlist, judul, deskripsi, jumlah_lagu, tanggal_dibuat, id_playlist, total_durasi)
                VALUES (%s,%s,%s,%s,%s,%s,%s,%s)
            """, [email, id_user_playlist, judul, deskripsi,0, date.today(),id_playlist,0])

            return redirect('manageplaylist:manage-playlist')

def edit_playlist(request, id_playlist):
    if request.method == "POST":
        judul = request.POST.get('judul')
        deskripsi = request.POST.get('deskripsi')

        with conn.cursor() as cursor:
            cursor.execute("""
                UPDATE USER_PLAYLIST
                SET judul = %s, deskripsi = %s
                WHERE id_user_playlist = %s
            """, [judul, deskripsi, id_playlist])

            print('berhasil!!')
            return redirect('manageplaylist:manage-playlist')



def delete_playlist(request, id_playlist):
    with conn.cursor() as cursor:
        cursor.execute("Set search_path to marmut;")
        cursor.execute("SELECT * FROM USER_PLAYLIST WHERE id_user_playlist = %s", [id_playlist])
        rows = cursor.fetchone()

        id = rows[6]

        cursor.execute("""
            DELETE FROM USER_PLAYLIST
            WHERE id_user_playlist = %s
        """, [id_playlist])

        cursor.execute("""
            DELETE FROM playlist
            WHERE id = %s
        """, [id])
        return redirect('manageplaylist:manage-playlist')

def showPlaylistPage(request, id_playlist):
    with conn.cursor() as cursor:
        try:
            cursor.execute("Set search_path to marmut;")
            cursor.execute("SELECT * FROM USER_PLAYLIST WHERE id_user_playlist = %s", [id_playlist])
            row = cursor.fetchone()

            email = row[0]

            cursor.execute("SELECT nama FROM AKUN WHERE email = %s", [email])
            pembuat = cursor.fetchone()[0]

            cursor.execute("""
                SELECT konten.judul, akun.nama, song.id_konten, konten.durasi
                FROM USER_PLAYLIST AS UP
                JOIN PLAYLIST_SONG AS PS ON UP.id_playlist = PS.id_playlist
                JOIN KONTEN ON PS.id_song = konten.id
                JOIN SONG ON PS.id_song = SONG.id_konten
                JOIN ARTIST ON SONG.id_artist = ARTIST.id
                JOIN AKUN ON ARTIST.email_akun = AKUN.email
                WHERE UP.id_user_playlist = %s;
            """, [id_playlist])
            songs = cursor.fetchall()

            detail = {
                'judul': row[2],
                'pembuat': pembuat,
                'jumlah_lagu': row[4],
                'total_durasi': row[7],
                'tanggal_dibuat':row[5],
                'deskripsi':row[3],
                'id_playlist': row[6],
            }

            song_list = [
                {
                    'judul': song[0],
                    'artist': song[1],
                    'id_konten': song[2],
                    'durasi': song[3]
                } for song in songs
            ]

            cursor.execute("""
                SELECT konten.judul, akun.nama, song.id_konten
                FROM SONG
                JOIN KONTEN ON SONG.id_konten = KONTEN.id
                JOIN ARTIST ON SONG.id_artist = ARTIST.id
                JOIN AKUN ON ARTIST.email_akun = AKUN.email;
            """)
            all_songs = cursor.fetchall()

            all_songs = [
                {
                    'judul': song[0],
                    'artist': song[1],
                    'id_konten': song[2],
                } for song in all_songs
            ]

            return render(request,"userplaylistdetail.html",{'detail' : detail, 'songs': song_list, 'all_songs':all_songs} )
            
        except Exception as e:
            msg = str(e).split('\n')[0]
            print( f' gagal: {msg}')
            return render(request,"userplaylistdetail.html",{} )

def add_song(request, id_playlist):
    if request.method == "POST":
        id_lagu = request.POST.get('song')

        with conn.cursor() as cursor:
            cursor.execute("Set search_path to marmut;")

            cursor.execute("""
                INSERT INTO PLAYLIST_SONG (id_playlist, id_song)
                VALUES (%s, %s)
            """, [id_playlist, id_lagu])

            cursor.execute("""
                SELECT COUNT(id_song)
                FROM PLAYLIST_SONG
                WHERE id_playlist = %s
            """, [id_playlist])
            jumlah_lagu = cursor.fetchone()[0]

            cursor.execute("""
                SELECT SUM(konten.durasi)
                FROM PLAYLIST_SONG
                JOIN SONG ON PLAYLIST_SONG.id_song = SONG.id_konten
                JOIN KONTEN ON konten.id = SONG.id_konten
                WHERE PLAYLIST_SONG.id_playlist = %s
            """, [id_playlist])
            total_durasi = cursor.fetchone()[0]

            cursor.execute("""
                UPDATE USER_PLAYLIST
                SET jumlah_lagu = %s, total_durasi = %s
                WHERE id_user_playlist = %s;
            """, [jumlah_lagu, total_durasi, id_playlist])

        return redirect('manageplaylist:manage-playlist')

def showPlayingSongPage(request, id_konten):
    with conn.cursor() as cursor:
        email = request.COOKIES.get("login")

        cursor.execute("Set search_path to marmut;")
        cursor.execute("""
            SELECT 
                konten.judul,
                akun.nama,
                konten.durasi,
                konten.tanggal_rilis,
                konten.tahun,    
                song.total_play,
                song.total_download,
                album.judul
            FROM 
                konten
            JOIN 
                song ON konten.id = song.id_konten
            JOIN
                album ON album.id = song.id_album
            JOIN
                artist ON artist.id = song.id_artist
            JOIN
                akun ON akun.email = artist.email_akun
            WHERE 
                konten.id = %s;
        """, [id_konten])
        song = cursor.fetchone()

        cursor.execute("""
            SELECT GENRE.genre
            FROM GENRE
            JOIN konten ON konten.id = GENRE.id_konten
            WHERE  konten.id = %s;
        """, [id_konten])
        genres = cursor.fetchall()

        cursor.execute("""
            SELECT  AKUN.nama
            FROM AKUN
            JOIN songwriter ON songwriter.email_akun = akun.email
            JOIN songwriter_write_song ON songwriter_write_song.id_songwriter = songwriter.id
            JOIN song ON song.id_konten = songwriter_write_song.id_song
            WHERE song.id_konten = %s;
        """, [id_konten])
        songwriters = cursor.fetchall()

        detail = {
            'id_song' : id_konten,
            'judul' : song[0],
            'genres' : [
                {
                    'genre': genre[0]
                } for genre in genres
            ],
            'artist': song[1],
            'songwriters': [
                {
                    'songwriter' : songwriter[0]
                } for songwriter in songwriters
            ],
            'durasi': song[2],
            'tanggal_rilis': song[3],
            'tahun': song[4],
            'total_play': song[5],
            'total_download': song[6],
            'album': song[7],
        }

        cursor.execute("""
            SELECT premium.email
            FROM premium
            WHERE premium.email = %s;
        """, [email])
        is_premium = cursor.fetchone()

        cursor.execute("""
            SELECT judul, id_user_playlist
            FROM USER_PLAYLIST
            WHERE email_pembuat = %s;
        """, [email])

        playlists = cursor.fetchall()

        playlists = [
            {
                'playlist' : playlist[0],
                'id': playlist[1]
            } for playlist in playlists
        ]

        context = {
            'detail': detail,
            'playlists': playlists,
            'show_navbar': True,
        }
        if is_premium:
            context = {
                'detail': detail,
                'premium':'premium',
                'playlists': playlists,
                'show_navbar': True,
            }
        


    return render(request,"playsong.html",context)

def add_song_to_playlist(request, id_konten):

manageplaylist/templates/manageplaylist.html
{% extends "base.html" %}
{% load static %}

{% block content %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>User Playlist</title>
    <style>
        body::after{
            content: "";
            background: url("https://i.ibb.co/kmFyJGY/background1.jpg")no-repeat center center fixed; 
            background-size: cover;
            top: 0;
            left: 0;
            bottom: 0;
            right: 0;
            position: absolute;
            height: 200%;
            z-index: -1;
        }

        .container {
            display: flex;
            justify-content: center;
            align-items: center;
            min-height: 100vh;
        }
    
        .list-playlist {
            background-color: #FDF2DE; 
            width: 80%; 
            padding: 20px;
            border-radius: 8px;
        }
    
        .tbtn {
            background-color: #FDD8A1;
            color: #09173E;
            padding: 8px 15px;
            border-radius: 9px;
            cursor: pointer;
            font-weight: bold;
            width: 120px; 
            display: block;
            margin: 4px;
            margin-left: auto;
            margin-right: auto;
        }
    
        .tbtn:hover{
            background-color: #09173E;
            color: #FDF2DE;
        }
        
        .add-btn{
            background-color:#09173E;
            color: #FDF2DE;
            padding: 8px 15px;
            border-radius: 9px;
            cursor: pointer;
            font-weight: bold;
            width: 300px; 
            display: block;
            margin-top: 20px;
            margin-left: auto;
            margin-right: auto;
        }
    
        .add-btn:hover{
            background-color: #FDD8A1;
            color: #09173E;
        }

        .modal {
            display: none; 
            position: fixed;
            z-index: 1;
            left: 0;
            top: 0;
            width: 100%;
            height: 100%;
            overflow: auto;
            background-color: rgba(0,0,0,0.5);
        }

        .modal-content {
            background-color: #09173E;
            margin: 10% auto;
            padding: 20px;
            border: 1px solid #6D7DB1;
            width: 80%;
            border-radius: 8px;
        }

        .close {
            color: #6D7DB1;
            float: right;
            font-size: 28px;
            font-weight: bold;
        }

        .close:hover,
        .close:focus {
            color: #FDF2DE;
            text-decoration: none;
            cursor: pointer;
        }

        .modal-header h2 {
            margin: 0;
            font-family: SangBleu;
            color: #FDF2DE;
            font-size: large;
            font-weight: bold;
            text-align: center;
        }

        .modal-body {
            margin-top: 20px;
        }

        .modal-body input[type="text"],
        .modal-body textarea {
            font-family: "TT Wellingtons";
            width: 100%;
            padding: 12px 20px;
            margin: 8px 0;
            display: inline-block;
            border: 1px solid #6D7DB1;
            border-radius: 4px;
            box-sizing: border-box;
        }

        .modal-footer {
            padding-top: 20px;
            text-align: center;
        }

        .modal-footer button {
            background-color: #6D7DB1;
            color: #FDF2DE;
            padding: 8px 15px;
            border-radius: 9px;
            cursor: pointer;
            font-weight: bold;
            width: 120px; 
            margin: 0 5px;
            border: none;
        }

        .modal-footer button:hover {
            background-color: #FDF2DE;
            color: #6D7DB1;
        }
    </style>
</head>
<body>
<div class="container">
    <div class="list-playlist">
        <h4 style="font-family: SangBleu; text-align: center; color: #09173E; font-size: 25px ; font-weight: bold;">USER PLAYLIST</h4>
        {% if playlists %}
        <table style="width: 80%; margin: 20px auto; border-collapse: collapse; background-color: #FDF2DE; border: 2px solid #09173E; border-radius: 8px;">
            <thead>
                <tr>
                    <th style="background-color: #09173E; color: #FDF2DE; font-size: 16px; font-weight: bold; padding: 10px;">Judul</th>
                    <th style="background-color: #09173E; color: #FDF2DE; font-size: 16px; font-weight: bold; padding: 10px;">Jumlah Lagu</th>
                    <th style="background-color: #09173E; color: #FDF2DE; font-size: 16px; font-weight: bold; padding: 10px;">Total Durasi</th>
                    <th style="background-color: #09173E; color: #FDF2DE; font-size: 16px; font-weight: bold; padding: 10px;">Action</th>
                </tr>
            </thead>
            <tbody>
                {% for playlist in playlists %}
                <tr>
                    <td style="padding: 10px; color:#09173E; text-align: center; font-family: TT Wellingtons;">{{ playlist.judul }}</td>
                    <td style="padding: 10px; color:#09173E; text-align: center; font-family: TT Wellingtons;">{{ playlist.jumlah_lagu }}</td>
                    <td style="padding: 10px; color:#09173E; text-align: center; font-family: TT Wellingtons;">{{ playlist.total_durasi }}</td>
                    <td style="padding: 10px; color:#09173E; text-align: center; font-family: TT Wellingtons;">
                        <form action="{% url 'manageplaylist:userplaylistdetail' playlist.id %}" method="post" style="display:inline;">
                            {% csrf_token %}
                            <button class="tbtn">Detail</button>
                        </form>
                        <button class="tbtn">Ubah</button>
                        <form action="{% url 'manageplaylist:delete-playlist' playlist.id %}" method="post" style="display:inline;">
                            {% csrf_token %}
                            <button type="submit" class="tbtn">Hapus</button>
                        </form>
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>

        {% else %}
        <p style="color: #09173E; font-size: 16px; font-weight: normal; padding: 10px; text-align: center;">Anda Belum Memiliki Playlist</p>
        {% endif %}

        <button id="add-btn" class="add-btn">Tambah Playlist</button>
    </div>

    <div id="addPlaylistModal" class="modal">
        <div class="modal-content">
            <span class="close">&times;</span>
            <div class="modal-header">
                <h2>Tambah Playlist</h2>
            </div>
            <div class="modal-body">
                <form id="addPlaylistForm" method="post" action="{% url 'manageplaylist:add-playlist' %}">
                    {% csrf_token %}
                    <input type="text" name="judul" placeholder="Judul" id="judul" required>
                    <textarea name="deskripsi" placeholder="Deskripsi" id="deskripsi" required></textarea>
                    <div class="modal-footer">
                        <button type="submit" id="submitBtn">Submit</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
</body>

<script>
    var addModal = document.getElementById("addPlaylistModal");
    var addBtn = document.getElementById("add-btn");
    var span = document.getElementsByClassName("close")[0];

    addBtn.onclick = function() {
        addModal.style.display = "block";
    }

    span.onclick = function() {
        modal.style.display = "none";
    }

    window.onclick = function(event) {
        if (event.target == addModal) {
            addModal.style.display = "none";
        }
    }
</script>
</html>
{% endblock content %}

manageplaylist/templates/userplaylistdetail.html
{% load static %}

{% block content %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <style>
        body{
            background: url("https://i.ibb.co.com/kmFyJGY/background1.jpg"); 
            background-size: cover; 
            background-repeat: no-repeat; 
            display: flex;
            justify-content: center; 
            align-items: center; 
            height: 100vh; 
            position: relative;
        }

        .list-lagu{
            background-color: #FDF2DE; 
            min-height: 90%; 
            width: 50%;
            padding: 5px;
            border-radius: 8px;
            overflow: auto;
        }

        .detail-playlist{
            background-color: transparent;
            height: 120%;
            width: 45%;
            padding: 5px;
            display: flex;
            flex-direction: column;
            justify-content: center;
            align-items: center;
        }

        .detail{
            background-color: #FDF2DE; 
            height: 35%; 
            width: 60%;
            padding: 5px;
            border-radius: 20px;
        }

        .tbtn {
            background-color: transparent;
            color: #09173E;
            padding: 5px 10px;
            border-radius: 10px;
            cursor: pointer;
            font-weight: bold;
            width: 120px; 
            display: block;
            margin: 4px;
            margin-left: auto;
            margin-right: auto;
        }
    
        .tbtn:hover{
            background-color: #09173E;
            color: #FDF2DE;
        }

        .add-btn{
            background-color:#09173E;
            color: #FDF2DE;
            padding: 8px 15px;
            border-radius: 9px;
            cursor: pointer;
            font-weight: bold;
            width: 300px; 
            display: block;
            margin-top: 20px;
            margin-left: auto;
            margin-right: auto;
        }

        .back-button {
            position: absolute; 
            left: 20px; 
            top: 20px; 
            background-color: #09173E;
            color: #FDF2DE;
            padding: 8px 15px;
            border-radius: 9px;
            cursor: pointer;
            font-weight: bold;
        }

        .back-button:hover,
        .shuffle-button:hover{
            background-color:#FDF2DE;
            color: #09173E;
        }

        .shuffle-button{
            background-color: #09173E; 
            color: #FDF2DE; 
            padding: 8px 15px; 
            border-radius: 9px; 
            cursor: pointer; 
            font-weight: bold; 
            margin-right: 10px;
            width: 200px; 
        }

        .modal {
            display: none; 
            position: fixed;
            z-index: 1;
            left: 0;
            top: 0;
            width: 100%;
            height: 100%;
            overflow: auto;
            background-color: rgba(0,0,0,0.5);
        }

        .modal-content {
            background-color: #09173E;
            margin: 10% auto;
            padding: 20px;
            border: 1px solid #6D7DB1;
            width: 80%;
            border-radius: 8px;
        }

        .close {
            color: #6D7DB1;
            float: right;
            font-size: 28px;
            font-weight: bold;
        }

        .close:hover,
        .close:focus {
            color: #FDF2DE;
            text-decoration: none;
            cursor: pointer;
        }

        .modal-header h2 {
            margin: 0;
            font-family: SangBleu;
            color: #FDF2DE;
            font-size: large;
            font-weight: bold;
            text-align: center;
        }

        .modal-body {
            margin-top: 20px;
        }

        .modal-body select {
            font-family: "TT Wellingtons";
            width: 100%;
            padding: 12px 20px;
            margin: 8px 0;
            display: inline-block;
            border: 1px solid #6D7DB1;
            border-radius: 4px;
            box-sizing: border-box;
            background-color: #FDF2DE;
            color: #09173E;
        }

        .modal-body select:focus {
            border: 1px solid #09173E;
            outline: none;
        }

        .modal-body select option {
            background-color: #FDF2DE;
            color: #09173E;
        }

        .modal-footer {
            padding-top: 20px;
            text-align: center;
        }

        .modal-footer button {
            background-color: #6D7DB1;
            color: #FDF2DE;
            padding: 8px 15px;
            border-radius: 9px;
            cursor: pointer;
            font-weight: bold;
            width: 120px;
            margin: 0 5px;
            border: none;
        }

        .modal-footer button:hover {
            background-color: #FDF2DE;
            color: #6D7DB1;
        }
    </style>
</head>
<body>
    <div class="detail-playlist">
        <h2 style="font-family: SangBleu; text-align: center; color: #FDF2DE; font-size: 26px; font-weight: bold;">User Playlist Detail</h2>

        <div class="detail">
            <p style="font-family: TT Wellingtons; text-align: center; color: #09173E; font-size: 20px; font-weight: bold;">{{detail.judul}}</p>
            <p style="font-family: TT Wellingtons; text-align: center; color: #09173E;">Pembuat: {{ detail.pembuat }}</p>
            <p style="font-family: TT Wellingtons; text-align: center; color: #09173E;">Jumlah Lagu: {{ detail.jumlah_lagu }}</p>
            <p style="font-family: TT Wellingtons; text-align: center; color: #09173E;">Total Durasi: {{ detail.total_durasi }}</p>
            <p style="font-family: TT Wellingtons; text-align: center; color: #09173E;">Tanggal Dibuat: {{ detail.tanggal_dibuat }}</p>
            <p style="font-family: TT Wellingtons; text-align: center; color: #09173E;">Deskripsi: {{ detail.deskripsi }}</p>
        </div>

        <div style="margin-top: 20px; text-align: center;">
            <button class="shuffle-button">Shuffle Play</button>
        </div>
    </div>

    <form action="{% url 'manageplaylist:manage-playlist'%}" method="post" style="display:inline;">
        {% csrf_token %}
        <button class="back-button">Back</button>
    </form>
    
    <div class="list-lagu">
        <h4 style="font-family: SangBleu; text-align: center; color:#09173E; font-size: 22px;">Daftar Lagu</h4>
        {% if songs %}
        <table style="width: 80%; margin: 20px auto; border-collapse: collapse; background-color: #FDF2DE; border: 2px solid #09173E; border-radius: 8px;">
            <thead>
                <tr>
                    <th style="background-color: #09173E; color: #FDF2DE; font-size: 16px; font-weight: bold; padding: 10px;">Judul Lagu</th>
                    <th style="background-color: #09173E; color: #FDF2DE; font-size: 16px; font-weight: bold; padding: 10px;">Oleh</th>
                    <th style="background-color: #09173E; color: #FDF2DE; font-size: 16px; font-weight: bold; padding: 10px;">Durasi</th>
                    <th style="background-color: #09173E; color: #FDF2DE; font-size: 16px; font-weight: bold; padding: 10px;">Actions</th>
                </tr>
            </thead>
            <tbody>
                {% for song in songs %}
                <tr>
                    <td style="padding: 10px; color:#09173E; text-align: center; font-family: TT Wellingtons;">{{song.judul}}</td>
                    <td style="padding: 10px; color:#09173E; text-align: center; font-family: TT Wellingtons;">{{song.artist}}</td>
                    <td style="padding: 10px; color:#09173E; text-align: center; font-family: TT Wellingtons;">{{song.durasi}}</td>
                    <td style="padding: 10px; color:#09173E; text-align: center; font-family: TT Wellingtons;">
                        <form action="{% url 'manageplaylist:playingsong' song.id_konten %}" method="post" style="display:inline;">
                            {% csrf_token %}
                            <button class="tbtn"">Lihat</button>
                        </form>
                        <button class="tbtn"">Play</button>
                        <form action="{% url 'manageplaylist:delete-song' detail.id_playlist song.id_konten %}" method="post" style="display:inline;">
                            {% csrf_token %}
                            <button type="submit" class="tbtn">Hapus</button>
                        </form>
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
        {% else %}
        <p style="color: #09173E; font-size: 16px; font-weight: normal; padding: 10px; text-align: center;">Anda Belum Memiliki Lagu</p>
        {% endif %}
        
        <button id="add-btn" class="add-btn">Tambah Lagu</button>
    </div>

    <div id="addSongModal" class="modal">
        <div class="modal-content">
            <span class="close">&times;</span>
            <div class="modal-header">
                <h2>Add Song</h2>
            </div>
            <div class="modal-body">
                <form id="addSongForm" method="post" action="{% url 'manageplaylist:add-song' detail.id_playlist %}">
                    {% csrf_token %}
                    <select name="song" id="song" required>
                        <option value="" disabled selected>Select a song</option>
                        {% for song in all_songs %}
                        <option value="{{ song.id_konten}}">{{ song.judul }} - {{ song.artist }}</option>
                        {% endfor %}
                    </select>
                    <div class="modal-footer">
                        <button type="submit" id="submitBtn">Submit</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</body>

<script>
    var addModal = document.getElementById("addSongModal");
    var addBtn = document.getElementById("add-btn");
    var span = document.getElementsByClassName("close")[0];

    addBtn.onclick = function() {
        addModal.style.display = "block";
    }

    span.onclick = function() {
        modal.style.display = "none";
    }

    window.onclick = function(event) {
        if (event.target == addModal) {
            addModal.style.display = "none";
        }
    }
</script>
</html>
{% endblock content %}